### ISSUE TITLE
any way to read timestamp from pcap file?

### ISSUE THREAD

**Issue by nicholaswbsr** [adriancostin6/emptyproject#3]
Hi
I'm study your project but I didn't find that you have any example to read timestamp from pcap file.
I also tried to do it but looks like the libtins has some issues as the timestamp value is wrong (always give the value based on current time instead of the value from pcap file).
I also tried to open issue on libtins, but I think it's better to ask you here. Expect you have some clue. 

Thanks.

**Comment by adriancostin6** [comment]
Hello @nicholaswbsr,

This is mostly a `libtins` question, and the answer can be found in the documentation. That being said, I understand that 
it is not the most clear, so I will try to help with some tips based on how I have been using it lately.

`libtins` provides an abstraction called `Packet` for capturing network packets, along with a timestamp.
Here is an example of how I would do it.

```cpp
// Reading timestamps for packets read from pcap file with libtins
#include <memory>
#include <exception>

#include <tins/tins.h>

class PacketSniffer {
public:
    PacketSniffer(const char *iface, const char *capture_filter) {
        Tins::SnifferConfiguration config;
        config.set_promisc_mode(true);
        config.set_filter(capture_filter);

        try {
            sniffer_ = std::make_unique<Tins::FileSniffer>(iface, config);
        } catch (const Tins::pcap_error &e) {
            throw std::runtime_error(e.what());
        } catch (const std::exception &e) {
            throw std::runtime_error(e.what());
        }
    }

    void run() {
        try {
            sniffer_->sniff_loop([](const Tins::Packet &packet) -> bool {
                                    // get the timestamp and do stuff with it here
                                    Tins::Timestamp ts = packet.timestamp();

                                    return true; // get next packet
                                 });
        } catch (const std::exception &ex) {
            throw std::runtime_error(ex.what());
        }
    }
private:
    std::unique_ptr<Tins::BaseSniffer> sniffer_;
};

int main() { 
    try {
        // leave filter blank to get all packets from pcap file
        PacketSniffer ps("/path/to/file", "");
        ps.run(); // run the sniffer and get the timestamps
    } catch (const std::exception &ex) {
        std::cout << ex.what();
    }
}

```

Do mind the fact that this is a minimal example, and I haven't had any time to test it.
It requires C++14 and compiling libtins with C++11 support, for sniffing `Packet` objects in the sniff loop. Hope it helps :)

**Comment by nicholaswbsr** [comment]
> Hello @nicholaswbsr,
> 
> This is mostly a `libtins` question, and the answer can be found in the documentation. That being said, I understand that it is not the most clear, so I will try to help with some tips based on how I have been using it lately.
> 
> `libtins` provides an abstraction called `Packet` for capturing network packets, along with a timestamp. Here is an example of how I would do it.
> 
> ```c++
> // Reading timestamps for packets read from pcap file with libtins
> #include <memory>
> #include <exception>
> 
> #include <tins/tins.h>
> 
> class PacketSniffer {
> public:
>     PacketSniffer(const char *iface, const char *capture_filter) {
>         Tins::SnifferConfiguration config;
>         config.set_promisc_mode(true);
>         config.set_filter(capture_filter);
> 
>         try {
>             sniffer_ = std::make_unique<Tins::FileSniffer>(iface, config);
>         } catch (const Tins::pcap_error &e) {
>             throw std::runtime_error(e.what());
>         } catch (const std::exception &e) {
>             throw std::runtime_error(e.what());
>         }
>     }
> 
>     void run() {
>         try {
>             sniffer_->sniff_loop([](const Tins::Packet &packet) -> bool {
>                                     // get the timestamp and do stuff with it here
>                                     Tins::Timestamp ts = packet.timestamp();
> 
>                                     return true; // get next packet
>                                  });
>         } catch (const std::exception &ex) {
>             throw std::runtime_error(ex.what());
>         }
>     }
> private:
>     std::unique_ptr<Tins::BaseSniffer> sniffer_;
> };
> 
> int main() { 
>     try {
>         // leave filter blank to get all packets from pcap file
>         PacketSniffer ps("/path/to/file", "");
>         ps.run(); // run the sniffer and get the timestamps
>     } catch (const std::exception &ex) {
>         std::cout << ex.what();
>     }
> }
> ```
> 
> Do mind the fact that this is a minimal example, and I haven't had any time to test it. It requires C++14 and compiling libtins with C++11 support, for sniffing `Packet` objects in the sniff loop. Hope it helps :)

Thank you very much for your quick reply!
I finally found that I made a mistake while I post.
Actually my last version of my test code is already get the timestamp correctly, but I didn't notice that, before I post.

Then I did more test and now I think it's more clear for me to understand. The key point is that only class Packet have the timestamp value not class PDU. So we must use the overload use "Packet&" as argument.

Here is my minimal example:

`
#include <vector>
#include <iostream>
#include <tins/tins.h>

using namespace Tins;

bool callback_1(PDU &pdu) {
    Packet packet = (Packet)pdu;
    auto sec = packet.timestamp().seconds();
    std::cout << "callback PDU &: " << sec << std::endl;
    return false;
}

bool callback_2(const PDU &pdu) {
    Packet packet = (Packet)pdu;
    auto sec = packet.timestamp().seconds();
    std::cout << "callback const PDU &: " << sec << std::endl;
    return false;
}

bool callback_3(Packet &pkt) {
    auto sec = pkt.timestamp().seconds();
    std::cout << "callback Packet &: " << sec << std::endl;
    return false;
}

bool callback_4(const Packet& pkt) {
    auto sec = pkt.timestamp().seconds();
    std::cout << "callback const Packet &: " << sec << std::endl;
    return false;
}

int main() {
    FileSniffer sniffer("../inputs/single_call_0006_7088.pcap");
    Packet some_pdu = sniffer.next_packet();
    //Packet packet = *some_pdu;
    auto sec = some_pdu.timestamp().seconds();
    std::cout << "next_packet: " << sec << std::endl;

    FileSniffer sniffer_1("../inputs/single_call_0006_7088.pcap");
    sniffer_1.sniff_loop(callback_1);

    FileSniffer sniffer_2("../inputs/single_call_0006_7088.pcap");
    sniffer_2.sniff_loop(callback_2);

    FileSniffer sniffer_3("../inputs/single_call_0006_7088.pcap");
    sniffer_3.sniff_loop(callback_3);

    FileSniffer sniffer_4("../inputs/single_call_0006_7088.pcap");
    sniffer_4.sniff_loop(callback_4);

    return 0;
   
}
` 

the callback_3 and callback_4 is good.
